name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.1.3'
          elixir-version: '1.12.3'

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['20.3', '21.3', '22.3', '23.3', '24.1']
        elixir: ['1.8', '1.9', '1.10', '1.11', '1.12']
        exclude:
          - otp: '20.3'
            elixir: '1.10'
          - otp: '20.3'
            elixir: '1.11'
          - otp: '20.3'
            elixir: '1.12'
          - otp: '21.3'
            elixir: '1.12'
          - otp: '23.3'
            elixir: '1.8'
          - otp: '23.3'
            elixir: '1.9'
          - otp: '24.1'
            elixir: '1.8'
          - otp: '24.1'
            elixir: '1.9'
          - otp: '24.1'
            elixir: '1.10'

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: MIX_ENV=test mix compile

      - name: Run tests
        run: mix test
